import {createHash} from 'node:crypto';
import {createServer} from 'node:http';
import {readFileSync} from 'node:fs';
import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {StreamableHTTPServerTransport} from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import {registerAppResource,registerAppTool,RESOURCE_MIME_TYPE} from '@modelcontextprotocol/ext-apps/server';
import {z} from 'zod';
const SOURCE='https://southernadd-cmyk.github.io/algoart/';
const WIDGET='ui://algoart/composition-picker.html';
const HTML=readFileSync(new URL('./public/picker.html',import.meta.url),'utf8');
const MODES={field:'Orbital Studies',spiral:'Golden Trajectories',rects:'Recursive Divisions',burst:'Radiant Systems',network:'Connected Fields',organic:'Growth Systems',geometric:'Constructed Forms',scribble:'Automatic Marks'};
const KEYS=Object.keys(MODES);
let chromiumInstance;
function safeMode(mode){if(!KEYS.includes(mode))throw Error('Unsupported original ALGO/ART mode');return mode;}
function safeSeed(seed){if(typeof seed!=='string'||!/^[\w.~-]{1,64}$/.test(seed))throw Error('Invalid seed');return seed;}
function seedFor(subject,mode,index){return 'CHAT-'+createHash('sha256').update(subject+'|'+mode+'|'+index+'|V6').digest('hex').slice(0,12).toUpperCase();}
async function browser(){if(!chromiumInstance){chromiumInstance=import('playwright').then(x=>x.chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']})).catch(e=>{chromiumInstance=undefined;throw e});}return chromiumInstance;}
function settings(mode,seed){return {mode,seed,elements:25,density:32,negativeSpace:82,phiStrength:95,grain:0,paper:'#ffffff',palette:'mono',colourCount:1,overdraw:1,opacity:92,thickness:12};}
async function originalPage(){const b=await browser();const page=await b.newPage({viewport:{width:1400,height:1000}});try{await page.goto(SOURCE+'?v=6',{waitUntil:'load',timeout:45000});await page.waitForFunction(()=>typeof window.AlgoArt?.render==='function'&&typeof window.AlgoArt?.readSettings==='function',{timeout:18000});return page;}catch(e){await page.close();throw e;}}
async function threeGuides(subject,requestedMode){const modeIndex=parseInt(createHash('sha256').update(subject).digest('hex').slice(0,6),16);const plans=[0,1,2].map(i=>{const mode=requestedMode||KEYS[(modeIndex+i*3)%8];return {id:String(i+1),mode,seed:seedFor(subject,mode,i),title:MODES[mode]};});const page=await originalPage();try{const rendered=await page.evaluate(plans=>{const A=window.AlgoArt;A.rendererVersion=6;const defaults=A.readSettings();return plans.map(p=>{const s=Object.assign({},defaults,{mode:p.mode,seed:p.seed,elements:25,density:32,negativeSpace:82,phiStrength:95,grain:0,paper:'#ffffff',palette:'mono',colourCount:1,overdraw:1,opacity:92,thickness:12});const c=document.createElement('canvas');const m=A.render(c,s,.25,false)||{};return {preview:c.toDataURL('image/png'),strategy:m.strategy||''};});},plans);return plans.map((p,i)=>Object.assign({},p,rendered[i]));}finally{await page.close();}}
async function selectedGuide(mode,seed){safeMode(mode);safeSeed(seed);const page=await originalPage();try{return await page.evaluate(({mode,seed})=>{const A=window.AlgoArt;A.rendererVersion=6;const s=Object.assign({},A.readSettings(),{mode,seed,elements:25,density:32,negativeSpace:82,phiStrength:95,grain:0,paper:'#ffffff',palette:'mono',colourCount:1,overdraw:1,opacity:92,thickness:12});const c=document.createElement('canvas');const meta=A.render(c,s,1,false)||{};return {image:c.toDataURL('image/png').split(',')[1],width:c.width,height:c.height,voids:(meta.voids||[]).map(v=>({x:v.x,y:v.y,w:v.w,h:v.h})),strategy:meta.strategy||''};},{mode,seed});}finally{await page.close();}}
function failure(e){return {isError:true,content:[{type:'text',text:'ALGO/ART rendering error: '+String(e?.message||e)}]};}
function makeMcp(){const m=new McpServer({name:'ALGO/ART Composition',version:'0.4.0'},{instructions:'Original ALGO/ART V6 compositions only. First invoke show_composition_picker, wait for selection, then call get_composition_guide. Generate the requested image using the actual returned PNG as the spatial reference, not just its text. Blank areas must remain clear. Never claim the image was generated if it was not.'});
registerAppResource(m,'ALGO/ART composition selector',WIDGET,{mimeType:RESOURCE_MIME_TYPE,description:'Three interactive original ALGO/ART composition previews'},async()=>({contents:[{uri:WIDGET,mimeType:RESOURCE_MIME_TYPE,text:HTML}]}));
registerAppTool(m,'show_composition_picker',{title:'Choose an ALGO/ART composition',description:'Present three visual compositions drawn using the exact original ALGO/ART V6 website algorithms, as an in-chat picker. Call first for ALGO/ART guided art.',inputSchema:{subject:z.string().max(600).default(''),mode:z.enum(KEYS).optional()},_meta:{ui:{resourceUri:WIDGET}},annotations:{readOnlyHint:true,openWorldHint:true}},async({subject='',mode})=>{try{return {content:[{type:'text',text:'Three original ALGO/ART compositions are displayed. Ask the user to choose one. Then call get_composition_guide with selected mode and seed before image generation.'}],structuredContent:{subject,engine:'ALGO/ART V6',guides:await threeGuides(subject,mode)}};}catch(e){return failure(e);}});
registerAppTool(m,'get_composition_guide',{title:'Get original ALGO/ART PNG guide',description:'Retrieve exact PNG for the selected original ALGO/ART V6 composition. Use its actual image as the visual reference when generating art, not merely the written description.',inputSchema:{mode:z.enum(KEYS),seed:z.string().min(1).max(64),subject:z.string().max(600).optional()},annotations:{readOnlyHint:true,openWorldHint:true}},async({mode,seed,subject=''})=>{try{const g=await selectedGuide(mode,seed);const text='ORIGINAL ALGO/ART V6 IMAGE REFERENCE: '+MODES[mode]+'; seed '+seed+'. Requested artwork: '+subject+'. Treat this PNG as a binding spatial blueprint. Preserve the placement, size, hierarchy and orientation of occupied areas, and leave every empty area blank. Do not fill negative space with scenery, patterns, textures, extra people or objects. Omit content that will not fit in occupied areas. Do not redraw the guide strokes as an overlay. Original protected void rectangles in 1400x1000 coordinates: '+JSON.stringify(g.voids)+'. The PNG is authoritative. Source: '+SOURCE+'?v=6&mode='+mode+'&seed='+seed;return {content:[{type:'text',text},{type:'image',data:g.image,mimeType:'image/png'}],structuredContent:{mode,seed,title:MODES[mode],subject,voids:g.voids,rendererVersion:6,source:SOURCE}};}catch(e){return failure(e);}});
return m;}
const PORT=Number(process.env.PORT||8787);
createServer(async(req,res)=>{const url=new URL(req.url||'/', 'http://localhost');if(url.pathname==='/health'){res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({status:'ok',engine:'ALGO/ART V6',endpoint:'/mcp'}));return;}if(url.pathname==='/mcp'&&req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'POST, GET, DELETE, OPTIONS','access-control-allow-headers':'content-type,authorization,mcp-session-id,mcp-protocol-version','access-control-expose-headers':'Mcp-Session-Id'});res.end();return;}if(url.pathname==='/mcp'&&['POST','GET','DELETE'].includes(req.method)){res.setHeader('access-control-allow-origin','*');res.setHeader('access-control-expose-headers','Mcp-Session-Id');const m=makeMcp(),transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined,enableJsonResponse:true});res.on('close',()=>{transport.close();m.close();});try{await m.connect(transport);await transport.handleRequest(req,res);}catch(e){console.error(e);if(!res.headersSent){res.writeHead(500);res.end('MCP server error');}}return;}res.writeHead(404);res.end('Not found');}).listen(PORT,'0.0.0.0',()=>console.log('ALGO/ART plugin listening on '+PORT));
